#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
    # shellcheck shell=bash
    # shellcheck source=/dev/null
    # shellcheck disable=2128

SET_DEBUG=${SET_DEBUG:-0} # set to 1 for verbose testing

git add --all
git commit --gpg-sign=$(git_gpg.php) -m "${1:-'Gitit bot: minor updates and formatting.'}"
git push --set-upstream origin $(git_current_branch)
git status