#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
# shellcheck shell=bash
# shellcheck source=/dev/null
# shellcheck disable=SC1090,SC2128,SC2178

#? ####################### debug
    # SET_DEBUG: set to 1 for verbose testing;
    #   set option -r for readonly (override future changes)
    declare -ix SET_DEBUG
    SET_DEBUG=${SET_DEBUG:-0}

#? ####################### initialization
    declare -x SSM_LOADED=${SSM_LOADED:='False'}

    declare -x SHELL_BIN="${SHELL##*/}"
    declare -x BASH_SOURCE="${BASH_SOURCE:-$0}"
    declare -x SCRIPT_NAME="${BASH_SOURCE##*/}"
    declare -x SCRIPT_PATH="${BASH_SOURCE%/*}"
    # echo -e "bin: $SHELL_BIN"
    # echo -e "bs: $BASH_SOURCE"
    # echo -e "name: $SCRIPT_NAME"
    # echo -e "path: $SCRIPT_PATH"

#? ######################## ssm modules
    . "$(which ssm_constants)"
    # . "$(command -v ssm_init)"
    . "$(which ssm_debug)"
    . "$(which ssm_usage)"

#? ####################### testing
    _run_tests() {
        for var in $(export -a | cut -d '=' -f 1); do
            # which_var $var
            attn "\$var: $var"
            attn "$(eval "value=\"\${$var}\"")"
            # shellcheck disable=SC2016
            attn '  \$${var}: '"$(eval echo -e "\$${var}")"
            if [[ $SHELL_BIN == 'zsh' ]]; then
                attn "  \${\!var}: ${(p)var}"
            else
                attn "  \${!var}: ${!var}"
            fi
        done
        }

#? ######################## main loop
    _main_loop() {
        #? ######################## project information
        [[ $SET_DEBUG == 1 ]] && echo "SSM loaded ... standard script modules for macOS."
        declare -x NAME && NAME=${NAME:-"${BASH_SOURCE##*/}"}
        # echo "NAME: $NAME"
        declare -x VERSION && VERSION=${VERSION:-'1.4.0'}
        declare -x DESC && DESC=${DESC:-'Script Resources for ssm on macOS'}
        declare -x USAGE && USAGE="${NAME:-'ssm'} [help|test|usage|version]"
        SSM_LOADED='True'
        set_man_page
        # [[ $SET_DEBUG == 1 ]] && _run_tests "$@"
        }

#! ######################## entry point
    if [[ $SSM_LOADED != 'True' ]]; then
        # echo "if SSM_LOADED: $SSM_LOADED"
        _main_loop "$@"
    fi
