#!/usr/bin/env zsh
# -*- coding: utf-8 -*-
    # shellcheck shell=bash
    # shellcheck source=/dev/null
    # shellcheck disable=2178,2128,2206,2034

# Do Over - run a command with args ... over and over and over ...
# it's just quicker and easier than debugging for short scripts
# add compile steps, CI pipeline stuff, logging ... whatever

COUNTER=0
SLEEP_INTERVAL=3
SCRIPT_NAME="${0##*/}"
SCRIPT_PATH="${0%/*}"
PID=$$

while true; do
    "$@"
    RETVAL=$?
    echo "${LIME:-}==============================================================${RESET:-}"
    echo "${MAIN:-}${SCRIPT_NAME}${CANARY:-} (PID $PID)"
    echo "${GO:-}${SCRIPT_PATH}"
    echo "${CHERRY:-}SLEEP = ${SLEEP_INTERVAL}  ${BLUE:-}COUNT = ${COUNTER}${ATTN:-}  RETVAL = ${RETVAL}${RESET:-}"
    ((COUNTER+=1))
    sleep $SLEEP_INTERVAL
done
